# Generated by Django 5.1.6 on 2025-03-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_file_keyentity_delete_drivefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document_type',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
